### ISSUE TITLE
Error Asana service

### ISSUE THREAD

**Issue by emulsion-io** [daskeyboard/daskeyboard-applet--asana#1]
Hi, 

I try to add my account, the oauth step is ok, but, when i look my notification, 

Error : The asana service returned error, StatusCodeError 400 - bad request, path /thirdparty/proxy/oauth2/proxy

Thanks

**Comment by fabiendv** [comment]
Hi,

I'll check. Do you have a premium Asana account?

Sorry for the wait.

**Comment by emulsion-io** [comment]
Hi,

Yes, it's with my premium asana account, but I haven't tested it for 1 year,

**Comment by fabiendv** [comment]
The error has been fixed and released.
You can enjoy Asana applet again.
